
source 'https://github.com/CocoaPods/Specs.git'
platform:ios,'7.0'
target 'EaseUIDemo' do
 pod 'HyphenateSDK', '~> 3.1.3'
 pod 'EaseUI', :git=>'https://github.com/3NCTO/easeui-ios-hyphenate-cocoapods.git', :tag => '3.2.1'
end
